### ISSUE TITLE
Evaluate Potential to Leverage Existing Cloud Security Alliance (CSA) CCM Control Catalog

### ISSUE THREAD

**Issue by mlysaght2017** [finos/common-cloud-controls#195]
### Description of Problem:
We want to evaluate whether the existing Cloud Security Alliance (CSA) Cloud Controls Matrix (CCM) can be leveraged or mapped to our project needs, so that we can avoid reinventing the wheel and utilize well-established standards to enhance the security posture assessment of CCC-defined cloud services.

**Acceptance Criteria:**

- Conduct a thorough review of the CSA CCM.
- Identify and document the similarities and differences between the CCM catalog and our project requirements.
- Create a mapping document that aligns our generic cloud services taxonomy with the controls in the existing catalogs.
- Assess the feasibility of adopting or adapting these controls to fit our project's goals.
- Provide recommendations on whether to use CCM, partially or fully, or to create a new catalog from scratch.
- Present findings and recommendations to the working group for a decision.

**Tasks:**

- [ ] Summarize the scope, structure, and key components of CSA CCM
- [ ] Highlight any gaps or areas that require customization.
- [ ] Assess the practical implications of adopting CSA CCM, considering factors such as compatibility, comprehensiveness, and potential modifications needed.
- [ ] Evaluate the resource requirements for adaptation versus creation of a new catalog.
- [ ] Document the findings, mapping, and feasibility assessment in a clear and concise manner.
- [ ] Prepare a presentation to share the findings and recommendations with the security working group.

**Stakeholders:**

Security WG Members
Duplication WG Members
 
**Priority:** High

**Estimated Effort:** 2-4 weeks

**Comment by mlysaght2017** [comment]
@eddie-knight @jared-lambert @robmoffat - Great first meeting with CSA CTO today:

**Present:** Daniele Catteddu [DC] , @rowan-baker, @mlysaght2017 

- Provided high-level overview of CCC, objectives and where we're at.
- Controls
  - DC mentioned a new CSA initiative working on more fine-grained technical control objectives - being released later this year.
  - We see opportunity to work together as it looks like CSA and CCC are working on some very similar goals, e.g., 
    - CSA starting from high level control abstraction working down to fine grain control objectives
    - CCC starting from finer-grain objectives working up to higher level control abstractions
    - Reconcile from both sides 
  - CSA is looking for representation from FSIs
- Assessments
  - STAR
    - self assessments
    - 3rd party 
    - new level: continuous assurance
- OSCAL
  - CCM in OSCAL
  - STAR not yet in OSCAL
 - Next steps:
   -  DC and team to provide a deep-dive walkthrough of new CSA control objective initiative on next call July 16th, 9am (New York) - invite sent - please let me know if you want to join

**Comment by iMichaela** [comment]
@mlysaght2017 - Can you please include me also in this meeting. Thank you
