### ISSUE TITLE
06/27/2024 Taxonomy Meeting Minutes

### ISSUE THREAD

**Issue by smendis-scottlogic** [finos/common-cloud-controls#227]
## Date

06/27/2024 - 11:30am ET / 4:30pm UK

- [Join Zoom Meeting](https://zoom.us/j/994109603410)
- Meeting ID: 941 0960 3410
- Passcode: 353234
- [Copy this meeting to your calendar](calendar.finos.org)
- [Find your local number](https://zoom.us/u/ab9zAHYy5T)

## Meeting notices

- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).
- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).
- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.
- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] [Project board](https://github.com/orgs/finos/projects/78/views/2) walkthrough
- [x] PR #224 Definition of Done
- [x] Issue #208 - Request collaboration
- [x] Issue #226 - How to create the milestones
- [x] AOB, Q&A & Adjourn (5mins)

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub usernameFullname, Capacity (Contributor/Advisor/Observer)
- ...

**Comment by eziogas-scottlogic** [comment]
Euthyme Ziogas / Scott Logic / Observer

**Comment by sshiells-scottlogic** [comment]
Stevie Shiells / Scott Logic

**Comment by dogle-scottlogic** [comment]
Dave Ogle / Scott Logic

**Comment by IMladjenovic** [comment]
Ivan Mladjenovic / Scott Logic

**Comment by smendis-scottlogic** [comment]
### Meeting Minutes

- Definition of Done
  - Should discuss with Community Structure WG where this document should reside
  - Should bring this to the all hands for discussion
- Database Categorization
  - Should identify what's missing in relational database service taxonomy
  - Abstract out the common functionality into the database level
  - Need more community support to work on this
  - Creating the .feature file assign to Eddie if needed for all taxonomies that have been defined already
- Milestone
  - Discuss with the Community Structure WG on guidelines on how to create the milestones
