### ISSUE TITLE
Define whether the working group wants to create a repo of component definitions

### ISSUE THREAD

**Issue by mcleo-d** [finos/common-cloud-controls#43]
_**Due date : 17th November 2023**_

This GitHub issues represents part of the roadmap defined by the OSCAL working group on https://github.com/finos/common-cloud-controls/issues/13
```[tasklist]
### Tasks
- [ ] Define whether the working group wants to create a repo of component definitions
- [ ] Define whether the working group wants to create an OSCAL catalog?
- [ ] Define whether the group needs a repo that is friendly for managing OSCAL content, catalogs and service definitions?
- [ ] Define whether the repo be a database or a GitHub repo?
- [ ] Potential for GitHub repo(s) that can be contributed via pull request
- [ ] Potential for cloud object storage that can be indexed and displayed.
- [ ] Potential for delivery pipeline from GitHub repo into other hosted service
```

**Comment by robmoffat** [comment]
@eddie-knight discussed using the existing CCC repo, and the existing directory structure, e.g.

```
services/
  database/
    relational/
      <oscal files here>
```

For each service there will be an OSCAL component, represented in XML, JSON and YAML.

Discussion for the maintainers about whether they want to do this.

@eddie-knight suggested to wait for the first PR to decide.
