### ISSUE TITLE
Define the tooling that should be used by the group / open source community?

### ISSUE THREAD

**Issue by mcleo-d** [finos/common-cloud-controls#44]
_**Due date : 15th December 2023**_

This GitHub issues represents part of the roadmap defined by the OSCAL working group on https://github.com/finos/common-cloud-controls/issues/13

```[tasklist]
### Tasks
- [ ] Define the tooling that should be used by the group / open source community?
- [ ] Should OSCAL be written by hand?
- [ ] How are the services described as OSCAL?
- [ ] Are there any editorial tools that enable automation of OSCAL?
- [ ] How should contributions be validated and accepted?
- [ ] Maybe other collaboration and editing solutions are better for the team?
```

**Comment by robmoffat** [comment]
@iMichaela having an OSCAL tool to help with formatting would be useful in the long run.  Simple examples can be easily written by hand, but this becomes problematic after a certain size.

@eddie-knight have we made clear the project's vision for OSCAL?

@iMichaela without tooling people are likely to become lost.

@eddie-knight It might be good to extract this from the white paper so that it's easy to read + absorb.

@iMichaela (the white paper) doesn't give a clear example of how the controls work yet.  Once you have the controls in a catalog, each component can show how they implement those controls.

Various tools for styling / displaying OSCAL in a human-friendly way.

**Comment by robmoffat** [comment]
https://github.com/oscal-club/awesome-oscal

suggested by @iMichaela

**Comment by robmoffat** [comment]
See also: https://oscal-compass.github.io/compliance-trestle/

**Comment by robmoffat** [comment]
Related: 

- #45

**Comment by crawfordchanel** [comment]
Closing: Mapped with issue #45
