### ISSUE TITLE
Implement an initial cloud service example that demonstrates a steel thread across working groups.

### ISSUE THREAD

**Issue by mcleo-d** [finos/common-cloud-controls#46]
_**Due date : 19th January 2024**_

This GitHub issues represents part of the roadmap defined by the OSCAL working group on https://github.com/finos/common-cloud-controls/issues/13

```[tasklist]
### Tasks
- [ ] Implement an initial cloud service example that demonstrates a steel thread across working groups.
- [ ] Pick initial common cloud services to define
- [ ] Allocate MITRE threats and apply OSCAL mitigations
- [ ] Write Gherkin tests to describe service configuration expectations
- [ ] Work with CSPs on how Gherkin should be interpreted via cloud APIs
```
